---
repositories:
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server

releases:
- name: metrics-server
  namespace: metrics-server
  chart: metrics-server/metrics-server
  version: 3.11.0
  values:
  - values.yaml
