apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: my-app
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
    - name: redis
      image: redis/redis-stack-server
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"