apiVersion: v1
kind: Service
metadata:
  name: redicheck-service
  namespace: my-app
spec:
  selector:
    app.kubernetes.io/name: redicheck
  type: NodePort
  ports:
    - protocol: TCP
      port: 5071
      targetPort: 5071